# Generated by Django 5.2.8 on 2026-01-06 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('email', models.CharField(db_collation='Polish_CI_AS', db_column='Email', max_length=255, unique=True)),
                ('passwordhash', models.TextField(db_collation='Polish_CI_AS', db_column='PasswordHash')),
                ('fullname', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='FullName', max_length=100, null=True)),
                ('role', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='Role', max_length=20, null=True)),
                ('weddingdate', models.DateField(blank=True, db_column='WeddingDate', null=True)),
                ('createdat', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Budgetcategories',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Polish_CI_AS', db_column='Name', max_length=50)),
            ],
            options={
                'db_table': 'BudgetCategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Budgetitems',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Polish_CI_AS', db_column='Name', max_length=200)),
                ('plannedamount', models.DecimalField(blank=True, db_column='PlannedAmount', decimal_places=2, max_digits=10, null=True)),
                ('actualamount', models.DecimalField(blank=True, db_column='ActualAmount', decimal_places=2, max_digits=10, null=True)),
                ('ispaid', models.BooleanField(blank=True, db_column='IsPaid', null=True)),
                ('notes', models.TextField(blank=True, db_collation='Polish_CI_AS', db_column='Notes', null=True)),
            ],
            options={
                'db_table': 'BudgetItems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Companyinfo',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='Email', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='Phone', max_length=50, null=True)),
                ('address', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='Address', max_length=255, null=True)),
                ('workinghours', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='WorkingHours', max_length=100, null=True)),
                ('workmode', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='WorkMode', max_length=100, null=True)),
            ],
            options={
                'db_table': 'CompanyInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contactmessages',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('sendername', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='SenderName', max_length=100, null=True)),
                ('senderemail', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='SenderEmail', max_length=200, null=True)),
                ('topic', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='Topic', max_length=50, null=True)),
                ('message', models.TextField(blank=True, db_collation='Polish_CI_AS', db_column='Message', null=True)),
                ('isread', models.BooleanField(blank=True, db_column='IsRead', null=True)),
                ('sentat', models.DateTimeField(blank=True, db_column='SentAt', null=True)),
            ],
            options={
                'db_table': 'ContactMessages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dietarypreferences',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Polish_CI_AS', db_column='Name', max_length=50)),
            ],
            options={
                'db_table': 'DietaryPreferences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faqcategories',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Polish_CI_AS', db_column='Name', max_length=100)),
                ('displayorder', models.IntegerField(blank=True, db_column='DisplayOrder', null=True)),
            ],
            options={
                'db_table': 'FaqCategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faqitems',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('question', models.CharField(db_collation='Polish_CI_AS', db_column='Question', max_length=300)),
                ('answer', models.TextField(db_collation='Polish_CI_AS', db_column='Answer')),
                ('isvisible', models.BooleanField(blank=True, db_column='IsVisible', null=True)),
            ],
            options={
                'db_table': 'FaqItems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Florists',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('companyname', models.CharField(db_collation='Polish_CI_AS', db_column='CompanyName', max_length=200)),
                ('title', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='Title', max_length=200, null=True)),
                ('city', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='City', max_length=100, null=True)),
                ('pricefrom', models.DecimalField(blank=True, db_column='PriceFrom', decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, db_collation='Polish_CI_AS', db_column='Description', null=True)),
                ('imageurl', models.TextField(blank=True, db_collation='Polish_CI_AS', db_column='ImageUrl', null=True)),
            ],
            options={
                'db_table': 'Florists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fullname', models.CharField(db_collation='Polish_CI_AS', db_column='FullName', max_length=200)),
                ('side', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='Side', max_length=50, null=True)),
                ('plusone', models.BooleanField(blank=True, db_column='PlusOne', null=True)),
                ('phone', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='Phone', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='Email', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, db_collation='Polish_CI_AS', db_column='Notes', null=True)),
            ],
            options={
                'db_table': 'Guests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gueststatuses',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Polish_CI_AS', db_column='Name', max_length=50)),
            ],
            options={
                'db_table': 'GuestStatuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guesttables',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('tablename', models.CharField(db_collation='Polish_CI_AS', db_column='TableName', max_length=50)),
                ('capacity', models.IntegerField(blank=True, db_column='Capacity', null=True)),
            ],
            options={
                'db_table': 'GuestTables',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Homesections',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('sectionkey', models.CharField(db_collation='Polish_CI_AS', db_column='SectionKey', max_length=50, unique=True)),
                ('title', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='Title', max_length=200, null=True)),
                ('subtitle', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='Subtitle', max_length=500, null=True)),
                ('buttontext', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='ButtonText', max_length=50, null=True)),
                ('imageurl', models.TextField(blank=True, db_collation='Polish_CI_AS', db_column='ImageUrl', null=True)),
            ],
            options={
                'db_table': 'HomeSections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Musicians',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Polish_CI_AS', db_column='Name', max_length=200)),
                ('city', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='City', max_length=100, null=True)),
                ('pricefrom', models.DecimalField(blank=True, db_column='PriceFrom', decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, db_collation='Polish_CI_AS', db_column='Description', null=True)),
                ('imageurl', models.TextField(blank=True, db_collation='Polish_CI_AS', db_column='ImageUrl', null=True)),
                ('rating', models.DecimalField(blank=True, db_column='Rating', decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': 'Musicians',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Musiciantypes',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Polish_CI_AS', db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'MusicianTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Newslettersubscribers',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('email', models.CharField(db_collation='Polish_CI_AS', db_column='Email', max_length=255, unique=True)),
                ('subscribedat', models.DateTimeField(blank=True, db_column='SubscribedAt', null=True)),
                ('isactive', models.BooleanField(blank=True, db_column='IsActive', null=True)),
            ],
            options={
                'db_table': 'NewsletterSubscribers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Photographers',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Polish_CI_AS', db_column='Name', max_length=200)),
                ('city', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='City', max_length=100, null=True)),
                ('pricefrom', models.DecimalField(blank=True, db_column='PriceFrom', decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, db_collation='Polish_CI_AS', db_column='Description', null=True)),
                ('imageurl', models.TextField(blank=True, db_collation='Polish_CI_AS', db_column='ImageUrl', null=True)),
            ],
            options={
                'db_table': 'Photographers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Photographerstyles',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Polish_CI_AS', db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'PhotographerStyles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sociallinks',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('platformname', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='PlatformName', max_length=50, null=True)),
                ('url', models.CharField(db_collation='Polish_CI_AS', db_column='Url', max_length=255)),
                ('iconname', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='IconName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'SocialLinks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staticpages',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('pagekey', models.CharField(db_collation='Polish_CI_AS', db_column='PageKey', max_length=50, unique=True)),
                ('title', models.CharField(db_collation='Polish_CI_AS', db_column='Title', max_length=200)),
                ('content', models.TextField(blank=True, db_collation='Polish_CI_AS', db_column='Content', null=True)),
                ('lastupdated', models.DateTimeField(blank=True, db_column='LastUpdated', null=True)),
            ],
            options={
                'db_table': 'StaticPages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taskpriorities',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Polish_CI_AS', db_column='Name', max_length=50)),
                ('colorcode', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='ColorCode', max_length=20, null=True)),
            ],
            options={
                'db_table': 'TaskPriorities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_collation='Polish_CI_AS', db_column='Title', max_length=255)),
                ('status', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='Status', max_length=20, null=True)),
                ('duedate', models.DateField(blank=True, db_column='DueDate', null=True)),
                ('notes', models.TextField(blank=True, db_collation='Polish_CI_AS', db_column='Notes', null=True)),
            ],
            options={
                'db_table': 'Tasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timelineevents',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_collation='Polish_CI_AS', db_column='Title', max_length=200)),
                ('details', models.TextField(blank=True, db_collation='Polish_CI_AS', db_column='Details', null=True)),
                ('iscompleted', models.BooleanField(blank=True, db_column='IsCompleted', null=True)),
            ],
            options={
                'db_table': 'TimelineEvents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timelinegroups',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Polish_CI_AS', db_column='Name', max_length=100)),
                ('orderindex', models.IntegerField(db_column='OrderIndex')),
            ],
            options={
                'db_table': 'TimelineGroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transporttypes',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Polish_CI_AS', db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'TransportTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transportvehicles',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Polish_CI_AS', db_column='Name', max_length=200)),
                ('city', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='City', max_length=100, null=True)),
                ('capacity', models.IntegerField(blank=True, db_column='Capacity', null=True)),
                ('pricefrom', models.DecimalField(blank=True, db_column='PriceFrom', decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, db_collation='Polish_CI_AS', db_column='Description', null=True)),
                ('imageurl', models.TextField(blank=True, db_collation='Polish_CI_AS', db_column='ImageUrl', null=True)),
            ],
            options={
                'db_table': 'TransportVehicles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userfavorites',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('serviceid', models.IntegerField(db_column='ServiceId')),
                ('servicetype', models.CharField(db_collation='Polish_CI_AS', db_column='ServiceType', max_length=50)),
                ('savedat', models.DateTimeField(blank=True, db_column='SavedAt', null=True)),
            ],
            options={
                'db_table': 'UserFavorites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Polish_CI_AS', db_column='Name', max_length=200)),
                ('city', models.CharField(db_collation='Polish_CI_AS', db_column='City', max_length=100)),
                ('capacity', models.IntegerField(db_column='Capacity')),
                ('priceperperson', models.DecimalField(db_column='PricePerPerson', decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, db_collation='Polish_CI_AS', db_column='Description', null=True)),
                ('imageurl', models.TextField(blank=True, db_collation='Polish_CI_AS', db_column='ImageUrl', null=True)),
                ('rating', models.DecimalField(blank=True, db_column='Rating', decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': 'Venues',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venuefeatures',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Polish_CI_AS', db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'VenueFeatures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Musicianstypemap',
            fields=[
                ('musicianid', models.ForeignKey(db_column='MusicianId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.musicians')),
            ],
            options={
                'db_table': 'MusiciansTypeMap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Photographerstylemap',
            fields=[
                ('photographerid', models.ForeignKey(db_column='PhotographerId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.photographers')),
            ],
            options={
                'db_table': 'PhotographerStyleMap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venuefeaturemap',
            fields=[
                ('venueid', models.ForeignKey(db_column='VenueId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.venues')),
            ],
            options={
                'db_table': 'VenueFeatureMap',
                'managed': False,
            },
        ),
    ]
